name: Deploy Node.js App to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Use any Node.js version that works for you

    - name: Install dependencies
      run: npm ci

    - name: Deploy to Ubuntu Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd /var/www/webstore-app # Change this to the app directory on your server
          git pull origin main
          npm ci
          pm2 restart app.js --name webstore-app # Use PM2 to restart the app

